/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.*;
import static jdk.nashorn.internal.codegen.OptimisticTypesPersistence.store;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author User
 */
public class NewJFrame1 extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    public NewJFrame1() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("store.png")));
        setTitle("Customise all products informaition");
        initComponents();
        conn=projectsqlconnetion.ConnecrDb();
        try{
			String query1 = "select max(bill_id) from sellproducts";
			PreparedStatement pst1 = conn.prepareStatement(query1);
			ResultSet rs1=pst1.executeQuery();
			rs1.next();
			billId = Integer.valueOf(rs1.getString(1));
			billId++;
			pst1.execute();
			pst1.close();
		}
		catch(Exception e)
		{
			System.out.println(e.getMessage());
		}
        clock();
    }public void clock()
	{
		Thread clock = new  Thread()
		{
			public void run()
			{
				try {
					
					for(;;)
						
					//while(true)
					{
						
					Calendar cal = new GregorianCalendar();
					int day = cal.get(Calendar.DAY_OF_MONTH);
					int month = cal.get(Calendar.MONTH);
					int year = cal.get(Calendar.YEAR);
					
					int second = cal.get(Calendar.SECOND);
					int minute = cal.get(Calendar.MINUTE);
					int hour = cal.get(Calendar.HOUR);
					
					jclock.setText("Time = "+hour+":"+minute+":"+second+"   Date: "+day+"/"+month+"/"+year+"");
					
					sleep(1000);
					}
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		};
		
		clock.start();
		
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Remove = new javax.swing.JButton();
        Modify = new javax.swing.JButton();
        New = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        jStock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScarch = new javax.swing.JTextField();
        jSerial = new javax.swing.JTextField();
        jName = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jCatagory = new javax.swing.JTextField();
        jPrice = new javax.swing.JTextField();
        jclock = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 51));

        jPanel1.setLayout(null);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Serial", "Name" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(190, 60, 80, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Serial");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 150, 40, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 190, 40, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Catagory");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 230, 60, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Scarch");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 70, 40, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Price");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 270, 37, 15);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel6.setText("Setting");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 0, 130, 23);

        Remove.setBackground(new java.awt.Color(255, 204, 204));
        Remove.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });
        jPanel1.add(Remove);
        Remove.setBounds(200, 370, 90, 60);

        Modify.setBackground(new java.awt.Color(255, 255, 153));
        Modify.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Modify.setText("Modify");
        Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyActionPerformed(evt);
            }
        });
        jPanel1.add(Modify);
        Modify.setBounds(100, 370, 90, 60);

        New.setBackground(new java.awt.Color(153, 255, 153));
        New.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        New.setText("New");
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });
        jPanel1.add(New);
        New.setBounds(10, 370, 80, 60);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 63, 90, 30);

        Table2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial", "Name", "Catagory", "Price", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(297, 100, 510, 378);

        jStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStockActionPerformed(evt);
            }
        });
        jPanel1.add(jStock);
        jStock.setBounds(150, 310, 135, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Stock");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 310, 40, 20);

        jScarch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jScarchActionPerformed(evt);
            }
        });
        jPanel1.add(jScarch);
        jScarch.setBounds(30, 100, 252, 30);

        jSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSerialActionPerformed(evt);
            }
        });
        jPanel1.add(jSerial);
        jSerial.setBounds(150, 150, 135, 30);

        jName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameActionPerformed(evt);
            }
        });
        jPanel1.add(jName);
        jName.setBounds(150, 190, 135, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Gallary");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(30, 20, 80, 30);
        jPanel1.add(jCatagory);
        jCatagory.setBounds(150, 230, 135, 30);

        jPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPriceActionPerformed(evt);
            }
        });
        jPanel1.add(jPrice);
        jPrice.setBounds(150, 270, 135, 30);

        jclock.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jclock.setText("clock");
        jPanel1.add(jclock);
        jclock.setBounds(630, 10, 190, 40);

        jButton2.setText("clear previous bills");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 443, 180, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/4k-Wallpapers-6.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 820, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         try{
					
					String selection = (String)jComboBox1.getSelectedItem();
					String query = "select * from products where "+selection+"=?";
					System.out.println( query);
					PreparedStatement pst=conn.prepareStatement(query);
					pst.setString(1,jScarch.getText());
					ResultSet rs = pst.executeQuery();
					Table2.setModel(DbUtils.resultSetToTableModel(rs));
					pst.close();	
					
				}
				catch (Exception ef){
				ef.printStackTrace();
				}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jStockActionPerformed

    private void jPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPriceActionPerformed

    private void jSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSerialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSerialActionPerformed

    private void jNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
			String query = "select * from products";
			PreparedStatement pst = conn.prepareStatement(query);
			ResultSet rs = pst.executeQuery();
			
			Table2.setModel(DbUtils.resultSetToTableModel(rs));
			
                        jSerial.setText("");
			jName.setText("");
			jCatagory.setText("");
			jPrice.setText("");
			jStock.setText("");
                        jScarch.setText("");
			pst.close();
			rs.close();
		}catch (Exception e){
			e.printStackTrace();	
		}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
        try
				{
					
					
					String query = " insert into products (Serial,Name,Catagory,Price,Stock) values (?,?,?,?,?)";
					PreparedStatement pst = conn.prepareStatement(query);
					
					if (jSerial.getText().equals(""))
					{
						pst.setString(1, null);
						
					}
					else {
						pst = conn.prepareStatement(query);
						pst.setString(1, jSerial.getText());
					}
                                        
					
					pst.setString(2,jName.getText());
					pst.setString(3,jCatagory.getText());
					pst.setString(4,jPrice.getText());
					pst.setString(5,jStock.getText());
					
					pst.execute();
					pst.close();
					
					JOptionPane.showMessageDialog(null, "Product Successfully added");
					
					
				} catch (Exception es) {
					es.printStackTrace();
				}

				 try{
			String query = "select * from products";
			PreparedStatement pst = conn.prepareStatement(query);
			ResultSet rs = pst.executeQuery();
			
			Table2.setModel(DbUtils.resultSetToTableModel(rs));
			
			pst.close();
			rs.close();
		}catch (Exception e){
			e.printStackTrace();	
		}
    }//GEN-LAST:event_NewActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        int action=JOptionPane.showConfirmDialog(null, "Do You Really Want To Remove This Product ?","Delete",JOptionPane.YES_NO_CANCEL_OPTION);
				if(action==0){
				try {
					String query="DELETE FROM `products` WHERE Serial='"+jSerial.getText()+"'";
					PreparedStatement pst = conn.prepareStatement(query);					
					pst.execute();
					
					JOptionPane.showMessageDialog(null, "Product Removed Successfully");
						
					pst.close();
				}
				catch(Exception ed){
					ed.printStackTrace();
				}
				try{
			String query = "select * from products";
			PreparedStatement pst = conn.prepareStatement(query);
			ResultSet rs = pst.executeQuery();
			
			Table2.setModel(DbUtils.resultSetToTableModel(rs));
			
			pst.close();
			rs.close();
		}catch (Exception e){
			e.printStackTrace();	
		}
			}
    }//GEN-LAST:event_RemoveActionPerformed

    private void ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyActionPerformed
        try
				{

					String query = "Update products set Serial ='"+jSerial.getText()+"',Name='"+jName.getText()+"',Catagory='"+jCatagory.getText()+"',Price='"+jPrice.getText()+"',Stock='"+jStock.getText()+"' where Serial ='"+jSerial.getText()+"'";
					PreparedStatement pst = conn.prepareStatement(query);
					
					pst.execute();
					
					JOptionPane.showMessageDialog(null, "Information modified");
					
					pst.close();
					
				} catch (Exception es) {
					es.printStackTrace();
				}

				

				try{
			String query = "select * from products";
			PreparedStatement pst = conn.prepareStatement(query);
			ResultSet rs = pst.executeQuery();
			
			Table2.setModel(DbUtils.resultSetToTableModel(rs));
			
			pst.close();
			rs.close();
		}catch (Exception e){
			e.printStackTrace();	
		}
    }//GEN-LAST:event_ModifyActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new sellingpage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jScarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jScarchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScarchActionPerformed

    private void Table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table2MouseClicked
       try{
					int row = Table2.getSelectedRow();
					String Serial_=(Table2.getModel().getValueAt(row, 0)).toString();
					
					String query = "select * from products where Serial='"+Serial_+"'";
					PreparedStatement pst = conn.prepareStatement(query);
					
					ResultSet rs = pst.executeQuery();
					
					
					while(rs.next())
					{
						jSerial.setText(rs.getString("Serial"));
						jName.setText(rs.getString("Name"));
						jCatagory.setText(rs.getString("Catagory"));
						jPrice.setText(rs.getString("Price"));
						jStock.setText(rs.getString("Stock"));
					}
					pst.close();
				}	
	
				catch (Exception ef){
				ef.printStackTrace();
				}
       try{
			String query = "select * from products";
			PreparedStatement pst = conn.prepareStatement(query);
			ResultSet rs = pst.executeQuery();
			
			Table2.setModel(DbUtils.resultSetToTableModel(rs));
			
			pst.close();
			rs.close();
		}catch (Exception e){
			e.printStackTrace();	
		}
       
    }//GEN-LAST:event_Table2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int action=JOptionPane.showConfirmDialog(null, "All of your previous bill's will be removed ?","Delete",JOptionPane.YES_NO_CANCEL_OPTION);
				if(action==0){
				try {
					String query="DELETE FROM `sellproducts` WHERE 1";
					PreparedStatement pst = conn.prepareStatement(query);					
					pst.execute();
					
					JOptionPane.showMessageDialog(null, "Cleared everything");
						
					pst.close();
				}
				catch(Exception ed){
					ed.printStackTrace();
				}
                                }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }
    public static int billId = 1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modify;
    private javax.swing.JButton New;
    private javax.swing.JButton Remove;
    private javax.swing.JTable Table2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JTextField jCatagory;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPrice;
    private javax.swing.JTextField jScarch;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jSerial;
    private javax.swing.JTextField jStock;
    private javax.swing.JLabel jclock;
    // End of variables declaration//GEN-END:variables
}
